language: python
python:
  - "2.7"
services:
 - memcached
 - mysql
install: "pip install -r requirements.txt"
before_script:
 - echo "SECRET_KEY='abcdefghijklmnopqrstuvwxyz123456789'" > settings/local.py
 - echo "DB_PASSWORD=''" >> settings/local.py
script: "./manage.py test"
