# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover_by',
            field=models.ManyToManyField(blank=True, to='libris.Creator'),
        ),
    ]
